### ISSUE TITLE
Using vhs from a `nix-shell` causes a panic from a "missing" file

### ISSUE THREAD

**Issue by jmcdo29** [charmbracelet/vhs#217]
I was wanting to try out `vhs` before committing to installing it so I installed it via `nix-shell -p vhs`. After generating a `.tape` file, when I tried to run `vhs < demo.tape` I got the following output

```
[launcher.Browser]2023/01/25 09:59:51 try to find the fastest host to download the browser binary
[launcher.Browser]2023/01/25 09:59:51 check https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1033860/chrome-linux.zip
[launcher.Browser]2023/01/25 09:59:51 check https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1033860/chrome-linux.zip
[launcher.Browser]2023/01/25 09:59:51 check https://playwright.azureedge.net/builds/chromium/1033860/chromium-linux-arm64.zip
[launcher.Browser]2023/01/25 09:59:52 check result: Get "https://registry.npmmirror.com/-/binary/chromium-browser-snapshots/Linux_x64/1033860/chrome-linux.zip": context canceled
[launcher.Browser]2023/01/25 09:59:52 check result: Get "https://playwright.azureedge.net/builds/chromium/1033860/chromium-linux-arm64.zip": context canceled
[launcher.Browser]2023/01/25 09:59:52 Download: https://storage.googleapis.com/chromium-browser-snapshots/Linux_x64/1033860/chrome-linux.zip
[launcher.Browser]2023/01/25 09:59:52 Progress:
[launcher.Browser]2023/01/25 09:59:52 00%
[launcher.Browser]2023/01/25 09:59:53 15%
[launcher.Browser]2023/01/25 09:59:54 35%
[launcher.Browser]2023/01/25 09:59:55 55%
[launcher.Browser]2023/01/25 09:59:56 75%
[launcher.Browser]2023/01/25 09:59:57 95%
[launcher.Browser]2023/01/25 09:59:57 100%
[launcher.Browser]2023/01/25 09:59:57 Unzip to: /home/jay/.cache/rod/browser/chromium-1033860
[launcher.Browser]2023/01/25 09:59:57 Progress:
[launcher.Browser]2023/01/25 09:59:57 00%
[launcher.Browser]2023/01/25 09:59:58 27%
[launcher.Browser]2023/01/25 09:59:59 48%
[launcher.Browser]2023/01/25 10:00:00 88%
[launcher.Browser]2023/01/25 10:00:00 100%
panic: fork/exec /home/jay/.cache/rod/browser/chromium-1033860/chrome-linux/chrome: no such file or directory

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0xd86700?, 0xc00025a0f0?})
	github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x25
github.com/go-rod/rod/lib/utils.E(...)
	github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:66
github.com/go-rod/rod/lib/launcher.(*Launcher).MustLaunch(0xc000432000?)
	github.com/go-rod/rod@v0.112.0/lib/launcher/launcher.go:351 +0x67
main.New()
	github.com/charmbracelet/vhs/vhs.go:67 +0x27b
main.Evaluate({0xc0000ac000, 0x865}, {0x145b420, 0xc00012e008}, {0x0, 0x0, 0x0?})
	github.com/charmbracelet/vhs/evaluator.go:33 +0x1c5
main.glob..func1(0x1a1bf20?, {0xc0004ff960, 0x1, 0x1?})
	github.com/charmbracelet/vhs/main.go:60 +0x16d
github.com/spf13/cobra.(*Command).execute(0x1a1bf20, {0xc000132010, 0x1, 0x1})
	github.com/spf13/cobra@v1.6.0/command.go:916 +0x862
github.com/spf13/cobra.(*Command).ExecuteC(0x1a1bf20)
	github.com/spf13/cobra@v1.6.0/command.go:1040 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.6.0/command.go:968
main.main()
	github.com/charmbracelet/vhs/main.go:135 +0x25
```

If I `ls ~/.cache/rod/browser/chromium-1033860/chrome-linux/` I do see that the `chrome` file exists

```sh
ls -l ~/.cache/rod/browser/chromium-1033860/chrome-linux/
.rwxr-xr-x 330M jay 25 Jan 10:00 chrome
.rwxr-xr-x 5.1k jay 25 Jan 10:00 chrome-wrapper
.rw-r--r-- 610k jay 25 Jan 10:00 chrome_100_percent.pak
.rw-r--r-- 914k jay 25 Jan 09:59 chrome_200_percent.pak
.rwxr-xr-x 1.9M jay 25 Jan 09:59 chrome_crashpad_handler
.rwxr-xr-x 349k jay 25 Jan 10:00 chrome_sandbox
drwxr-xr-x    - jay 25 Jan 10:00 ClearKeyCdm
.rw-r--r--  10M jay 25 Jan 10:00 icudtl.dat
.rwxr-xr-x 403k jay 25 Jan 10:00 libEGL.so
.rwxr-xr-x 8.9M jay 25 Jan 10:00 libGLESv2.so
.rwxr-xr-x 6.2M jay 25 Jan 09:59 libvk_swiftshader.so
.rwxr-xr-x 845k jay 25 Jan 10:00 libvulkan.so.1
drwxr-xr-x    - jay 25 Jan 10:00 locales
drwxr-xr-x    - jay 25 Jan 10:00 MEIPreload
.rwxr-xr-x 4.2M jay 25 Jan 09:59 nacl_helper
.rwxr-xr-x 9.9k jay 25 Jan 10:00 nacl_helper_bootstrap
.rwxr-xr-x 3.9M jay 25 Jan 10:00 nacl_irt_x86_64.nexe
.rw-r--r-- 2.5k jay 25 Jan 10:00 product_logo_48.png
drwxr-xr-x    - jay 25 Jan 10:00 resources
.rw-r--r-- 8.3M jay 25 Jan 09:59 resources.pak
.rw-r--r-- 745k jay 25 Jan 10:00 v8_context_snapshot.bin
.rw-r--r--  107 jay 25 Jan 10:00 vk_swiftshader_icd.json
.rwxr-xr-x  37k jay 25 Jan 10:00 xdg-mime
.rwxr-xr-x  33k jay 25 Jan 10:00 xdg-settings
```

It also seems that it's trying to redownload the chromium zip every time I run `vhs < demo.tape`, not sure if that's related or not.

## Steps to reproduce

1) `nix-shell -p vhs`
2) `vhs new demo`
3) `vhs < demo`
4) Observe error

## Other information

`nix-info`

```
nix-info      
system: "x86_64-linux", multi-user?: yes, version: nix-env (Nix) 2.11.1, channels(root): "home-manager, nixos-22.11, nixos-unstable", nixpkgs: /nix/var/nix/profiles/per-user/root/channels/nixos
```

Shell: zsh

**Comment by archite** [comment]
I've found this works for when I want to use *vhs*:

```nix
{ pkgs ? import <nixpkgs> {} }:

let
  fhs = pkgs.buildFHSUserEnvBubblewrap {
    name = "vhs-env";
    targetPkgs = pkgs: (with pkgs; [
      chromium
      vhs
    ]);
    runScript = "${pkgs.zsh}/bin/zsh";
  };
in fhs.env
```

**Comment by slinlee** [comment]
Thanks @archite . I found the key part was making sure chromium was installed so that `vhs` didn't try to install it itself.

This could be made smoother with different behavior for nix or a message if chromium isn't detected on nix.

**Comment by archite** [comment]
On nix, if the chromium were already there, it would use the local store path and if not, it would pull it down and remain until `gc` would run. I'd suggest just documenting that the two should go hand-in-hand. I have been running `vhs` headless and haven't found pulling chromium and it's dependencies to be too much of a pain.

I used FHS as an example only because I figured it would provided a more isolated example but so long as the two packages are available, it works well enough for me.

**Comment by slinlee** [comment]
This is also tracked here in this bug  https://github.com/NixOS/nixpkgs/issues/208002
I added a fix that's waiting to be merge here: https://github.com/NixOS/nixpkgs/pull/216224 (Thanks @maaslalani for the quick review!)

**Comment by archite** [comment]
Yeah, a change [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/misc/vhs/default.nix#L17) to add chromium would do it.

**Comment by caarlos0** [comment]
this seems to have been fixed, closing!
