### ISSUE TITLE
Bug: "Panic: EOF" while trying to read any .tape files

### ISSUE THREAD

**Issue by OXY2DEV** [charmbracelet/vhs#548]
**Describe the bug**
I created a `test.tape` file with the code block in the README.

```tape
# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "echo 'Welcome to VHS!'"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s
```
I tried running it via `vhs test.tape`. But I get this error.

```text
File: test.tape
panic: EOF

goroutine 1 [running]:
github.com/go-rod/rod/lib/utils.glob..func2({0x56f91bf900?, 0x56f989a6a0?})
        /home/builder/go/pkg/mod/github.com/go-rod/rod@v0.112.0/lib/utils/utils.go:60 +0x24
github.com/go-rod/rod.genE.func1({0x40000ab0b0?, 0x40000f82d0?, 0x16?})
        /home/builder/go/pkg/mod/github.com/go-rod/rod@v0.112.0/must.go:36 +0x64
github.com/go-rod/rod.(*Browser).MustPage(0x4000178a20, {0x400055f5a8?, 0x400055f5b8?, 0x1?})
        /home/builder/go/pkg/mod/github.com/go-rod/rod@v0.112.0/must.go:71 +0xec
main.New()
        /home/builder/.termux-build/vhs/src/vhs.go:93 +0x2ac
main.Evaluate({0x56f92c3438, 0x40004139c0}, {0x40000fc000, 0x14f}, {0x56f92bf020, 0x4000010018}, {0x400055fcc0, 0x1, 0x0?})
        /home/builder/.termux-build/vhs/src/evaluator.go:25 +0x140
main.glob..func1(0x56f98a78c0, {0x4000486c50, 0x1, 0x1?})
        /home/builder/.termux-build/vhs/src/main.go:67 +0x1cc
github.com/spf13/cobra.(*Command).execute(0x56f98a78c0, {0x4000020050, 0x1, 0x1})
        /home/builder/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:916 +0x5c4
github.com/spf13/cobra.(*Command).ExecuteC(0x56f98a78c0)
        /home/builder/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:1044 +0x340
github.com/spf13/cobra.(*Command).Execute(...)
        /home/builder/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:968
github.com/spf13/cobra.(*Command).ExecuteContext(...)
        /home/builder/go/pkg/mod/github.com/spf13/cobra@v1.6.1/command.go:961
main.main()
        /home/builder/.termux-build/vhs/src/main.go:186 +0xe4
```

It doesn't matter which file I use or what the content of the file is. So, I can't identify the source of the issue.

**Setup**
Please complete the following information along with version numbers, if applicable.
 - OS: Android 13
 - Shell: fish
 - Terminal Emulator: Termux
 - Terminal Multiplexer: none

**To Reproduce**
1. Create a new tape files `touch test.tape` or via `vhs > test.tape`.
2. Do anything.
3. Exit.
4. Run `vhs test.tape`.

Alternative,

1. Create a new `test.tape` file and paste any code to the file.
2. Run `vhs test.tape`.

**Source Code**
For the sake of reproducing the bug. I have used the example in the README.md file.

```tape
# Where should we write the GIF?
Output demo.gif

# Set up a 1200x600 terminal with 46px font.
Set FontSize 46
Set Width 1200
Set Height 600

# Type a command in the terminal.
Type "echo 'Welcome to VHS!'"

# Pause for dramatic effect...
Sleep 500ms

# Run the command by pressing enter.
Enter

# Admire the output for a bit.
Sleep 5s
```

**Expected behavior**
No error should occur.

**Screenshots**
![Screenshot_2024-11-14-07-55-46-125_com termux-edit](https://github.com/user-attachments/assets/335590c6-086c-4794-b642-3473a02eb1e3)

**Additional context**
None

**Comment by OXY2DEV** [comment]
I found the issue, you actually need to have a graphical environment for this.

In my case, I use `termux-x11`.

Unfortunately, the output was an empty gif. I will see if I can get it to work somehow.

I will be closing this issue now.
